CREATE TABLE albums (
	id VARCHAR PRIMARY KEY,
	title TEXT NOT NULL,
	artist TEXT NOT NULL,
	price FLOAT NOT NULL
);

CREATE TABLE users (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	email VARCHAR NOT NULL UNIQUE,
	fullname VARCHAR NOT NULL,
	password VARCHAR(60) NOT NULL
);

